### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by W1ldAustin** [DualCoder/vgpu_unlock#83]
Hello there,

I have ran into an issue where it is not running. After running the file itself I get the following:

`Traceback (most recent call last):
  File "./vgpu_unlock", line 246, in <module>
    main()
  File "./vgpu_unlock", line 230, in main
    if sys.argv[1] != "-f":
IndexError: list index out of range
`

I don't know if that is the issue for it not wanting to run, but that's what I suspect, as that's what I get while trying to run it. I did have to modify a few things in the code, including changing the path of where python3 was, but this is an issue I have no clue on what to do, and I couldn't find anything about it.

Thank you,
Austin Zechar

**Comment by W1ldAustin** [comment]
Update: found out that was normal when running the file without the driver file. I now have a new issue:

The systemctl file when run now displays this:

Nov 18 04:32:43 BillyBoy nvidia-vgpud[3151]: vGPU types: 401
Nov 18 04:32:43 BillyBoy nvidia-vgpud[3151]: 
Nov 18 04:32:43 BillyBoy nvidia-vgpud[3165]: vgpu_unlock loaded.
Nov 18 04:32:43 BillyBoy modprobe[3165]: vgpu_unlock loaded.
Nov 18 04:32:43 BillyBoy nvidia-vgpud[3151]: error: failed to allocate client: 59
Nov 18 04:32:43 BillyBoy nvidia-vgpud[3151]: error: failed to read pGPU information: 9
Nov 18 04:32:43 BillyBoy nvidia-vgpud[3151]: error: failed to send vGPU configuration info to RM: 9
Nov 18 04:32:43 BillyBoy nvidia-vgpud[3151]: PID file unlocked.
Nov 18 04:32:43 BillyBoy nvidia-vgpud[3151]: PID file closed.
Nov 18 04:32:43 BillyBoy nvidia-vgpud[3151]: Shutdown (3151)

**Comment by W1ldAustin** [comment]
hello?

**Comment by SansSerif1** [comment]
@W1ldAustin Hello, tried to unlock my gpu today and ended with this same problem (failed to allocate client 59, etc etc). Have you managed to fix it somehow? Thanks.
