### ISSUE TITLE
frida.NotSupportedError last known good frida version?

### ISSUE THREAD

**Issue by tobiashagen7** [DualCoder/vgpu_unlock#85]
Hi, I'm currently trying my to attempt to install vgpu unlock on my system, spoofing my Tesla M40 24GB as a M60. 
I have drivers 460.91.03 installed on Kernel 5.4.162.

I'm using frida==15.1.12 but there seems to be some issue with it. Here's my systemd output for nvidia-gpu-mgr:

```tobias@tobias-X570-AORUS-MASTER:~$ journalctl -u nvidia-vgpu-mgr
-- Journal begins at Tue 2021-11-30 13:33:21 ACST, ends at Wed 2021-12-01 00:57:39 ACST. --
Nov 30 23:33:11 tobias-X570-AORUS-MASTER systemd[1]: Starting NVIDIA vGPU Manager Daemon...
Nov 30 23:33:11 tobias-X570-AORUS-MASTER systemd[1]: Started NVIDIA vGPU Manager Daemon.
Nov 30 23:33:15 tobias-X570-AORUS-MASTER nvidia-vgpu-mgr[891]: notice: vmiop_env_log: nvidia-vgpu-mgr daemon started
Nov 30 23:42:50 tobias-X570-AORUS-MASTER systemd[1]: Stopping NVIDIA vGPU Manager Daemon...
Nov 30 23:42:50 tobias-X570-AORUS-MASTER systemd[1]: nvidia-vgpu-mgr.service: Deactivated successfully.
Nov 30 23:42:50 tobias-X570-AORUS-MASTER systemd[1]: Stopped NVIDIA vGPU Manager Daemon.
-- Boot fa4b663e8a6c4ba2a2b68d47e40b8cc5 --
Nov 30 23:43:29 tobias-X570-AORUS-MASTER systemd[1]: Starting NVIDIA vGPU Manager Daemon...
Nov 30 23:43:29 tobias-X570-AORUS-MASTER systemd[1]: Started NVIDIA vGPU Manager Daemon.
Nov 30 23:43:33 tobias-X570-AORUS-MASTER nvidia-vgpu-mgr[907]: notice: vmiop_env_log: nvidia-vgpu-mgr daemon started
Nov 30 23:52:39 tobias-X570-AORUS-MASTER systemd[1]: Stopping NVIDIA vGPU Manager Daemon...
Nov 30 23:52:39 tobias-X570-AORUS-MASTER systemd[1]: nvidia-vgpu-mgr.service: Deactivated successfully.
Nov 30 23:52:39 tobias-X570-AORUS-MASTER systemd[1]: Stopped NVIDIA vGPU Manager Daemon.
-- Boot 6ab3a4cd917a4fabbe016437b459b229 --
Nov 30 23:53:23 tobias-X570-AORUS-MASTER systemd[1]: Starting NVIDIA vGPU Manager Daemon...
Nov 30 23:53:23 tobias-X570-AORUS-MASTER systemd[1]: Started NVIDIA vGPU Manager Daemon.
Nov 30 23:53:24 tobias-X570-AORUS-MASTER vgpu_unlock[971]: Traceback (most recent call last):
Nov 30 23:53:24 tobias-X570-AORUS-MASTER vgpu_unlock[971]:   File "/root/vgpu_unlock/vgpu_unlock", line 246, in <module>
Nov 30 23:53:24 tobias-X570-AORUS-MASTER vgpu_unlock[971]:     main()
Nov 30 23:53:24 tobias-X570-AORUS-MASTER vgpu_unlock[971]:   File "/root/vgpu_unlock/vgpu_unlock", line 236, in main
Nov 30 23:53:24 tobias-X570-AORUS-MASTER vgpu_unlock[971]:     instrument(pid)
Nov 30 23:53:24 tobias-X570-AORUS-MASTER vgpu_unlock[971]:   File "/root/vgpu_unlock/vgpu_unlock", line 190, in instrument
Nov 30 23:53:24 tobias-X570-AORUS-MASTER vgpu_unlock[971]:     session = device.attach(pid)
Nov 30 23:53:24 tobias-X570-AORUS-MASTER vgpu_unlock[971]:   File "/usr/local/lib/python3.9/dist-packages/frida/core.py", line 26, in wrapper
Nov 30 23:53:24 tobias-X570-AORUS-MASTER vgpu_unlock[971]:     return f(*args, **kwargs)
Nov 30 23:53:24 tobias-X570-AORUS-MASTER vgpu_unlock[971]:   File "/usr/local/lib/python3.9/dist-packages/frida/core.py", line 165, in attach
Nov 30 23:53:24 tobias-X570-AORUS-MASTER vgpu_unlock[971]:     return Session(self._impl.attach(self._pid_of(target), *args, **kwargs))
Nov 30 23:53:24 tobias-X570-AORUS-MASTER vgpu_unlock[971]: frida.NotSupportedError: remote_exec PTRACE_CONT wait failed: 0
Nov 30 23:53:24 tobias-X570-AORUS-MASTER systemd[1]: nvidia-vgpu-mgr.service: Main process exited, code=exited, status=1/FAILURE
Nov 30 23:53:24 tobias-X570-AORUS-MASTER systemd[1]: nvidia-vgpu-mgr.service: Failed with result 'exit-code'.
-- Boot a836c56117294b8f854021f6ae601ddd --
Dec 01 00:00:59 tobias-X570-AORUS-MASTER systemd[1]: Starting NVIDIA vGPU Manager Daemon...
Dec 01 00:00:59 tobias-X570-AORUS-MASTER systemd[1]: Started NVIDIA vGPU Manager Daemon.
Dec 01 00:01:00 tobias-X570-AORUS-MASTER vgpu_unlock[977]: Traceback (most recent call last):
Dec 01 00:01:00 tobias-X570-AORUS-MASTER vgpu_unlock[977]:   File "/root/vgpu_unlock/vgpu_unlock", line 246, in <module>
Dec 01 00:01:00 tobias-X570-AORUS-MASTER vgpu_unlock[977]:     main()
Dec 01 00:01:00 tobias-X570-AORUS-MASTER vgpu_unlock[977]:   File "/root/vgpu_unlock/vgpu_unlock", line 236, in main
Dec 01 00:01:00 tobias-X570-AORUS-MASTER vgpu_unlock[977]:     instrument(pid)
Dec 01 00:01:00 tobias-X570-AORUS-MASTER vgpu_unlock[977]:   File "/root/vgpu_unlock/vgpu_unlock", line 190, in instrument
Dec 01 00:01:00 tobias-X570-AORUS-MASTER vgpu_unlock[977]:     session = device.attach(pid)
Dec 01 00:01:00 tobias-X570-AORUS-MASTER vgpu_unlock[977]:   File "/usr/local/lib/python3.9/dist-packages/frida/core.py", line 26, in wrapper
Dec 01 00:01:00 tobias-X570-AORUS-MASTER vgpu_unlock[977]:     return f(*args, **kwargs)
Dec 01 00:01:00 tobias-X570-AORUS-MASTER vgpu_unlock[977]:   File "/usr/local/lib/python3.9/dist-packages/frida/core.py", line 165, in attach
Dec 01 00:01:00 tobias-X570-AORUS-MASTER vgpu_unlock[977]:     return Session(self._impl.attach(self._pid_of(target), *args, **kwargs))
Dec 01 00:01:00 tobias-X570-AORUS-MASTER vgpu_unlock[977]: frida.NotSupportedError: remote_exec PTRACE_CONT wait failed: 0
Dec 01 00:01:00 tobias-X570-AORUS-MASTER systemd[1]: nvidia-vgpu-mgr.service: Main process exited, code=exited, status=1/FAILURE
Dec 01 00:01:00 tobias-X570-AORUS-MASTER systemd[1]: nvidia-vgpu-mgr.service: Failed with result 'exit-code'.
-- Boot 43ad9fed9fa3444b860504c7d4f300ba --
Dec 01 00:04:51 tobias-X570-AORUS-MASTER systemd[1]: Starting NVIDIA vGPU Manager Daemon...```

Any help appreciated. :)

**Comment by tobiashagen7** [comment]
Solved by using [vgpu_unlock-rs](https://github.com/mbilker/vgpu_unlock-rs) in combination with this to get unlock working.
